// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6zqYX0dxVelnESibRiVuBqF0h0xdGYo',
    appId: '1:736716966680:web:d35e682e328ff971956c6d',
    messagingSenderId: '736716966680',
    projectId: 'marvellous-e-commerce',
    authDomain: 'marvellous-e-commerce.firebaseapp.com',
    storageBucket: 'marvellous-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsqzk7GW46XOTGFceBjl2s9HA-W-vF7o',
    appId: '1:736716966680:android:27baebbc5258ba85956c6d',
    messagingSenderId: '736716966680',
    projectId: 'marvellous-e-commerce',
    storageBucket: 'marvellous-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTCszq8Vv-DPl-XuaSU_v7Iw5svRtTk-E',
    appId: '1:736716966680:ios:830ecf83a08cdf11956c6d',
    messagingSenderId: '736716966680',
    projectId: 'marvellous-e-commerce',
    storageBucket: 'marvellous-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.marvellousAdmin',
  );
}
